search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]    

shop2shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('search/', include('search.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
#추가
from django.contrib.auth import views as auth_views
from django.conf.urls import url


urlpatterns = [
    path('', views.StoreView.as_view(), name="store"),
    #path('', views.store, name="store"),
    path('cart/', views.CartView.as_view(), name="cart"),
    #path('cart/', views.cart, name="cart"),
    path('checkout/', views.CheckoutView.as_view(), name="checkout"),
    #path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.UpdatedItemView.as_view(), name="update_item"),
    #path('update_item/', views.updatedItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    #추가
    path('register/', views.RegistrationView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="store/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail"),
    path('add-product/', views.ProductAddView.as_view(), name="add_product"),
    path('product/<int:pk>/comment/', views.add_comment, name="add_comment"),     
    path('product/<int:pk>/remove/', views.comment_remove, name="comment_remove"),   
    path('product/<int:pk>/modify/', views.comment_modify, name='comment_modify'),
    
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

class Customer(models.Model):
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        #return self.user.username 아님
        return self.name

      

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url        

@receiver(post_save,sender=User)
def create_or_update_customer(sender, instance, created, **kwargs):
    """
    Create or update the customer
    """
    if created:
        # 기존 Customer.objects.create(user=instance) 에서 시그날 추가 - name, email        
        Customer.objects.create(user=instance,name=instance.username,email=instance.email)
    # 이미 존재하는 user: 그냥 customer 저장 
    instance.customer.save()    


class Comment(models.Model):
    product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    modify_date = models.DateTimeField(null=True, blank=True)
    approved_comment = models.BooleanField(default=True)

    
    def __str__(self): 
        return self.text    

class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    dated_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transation_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for z in orderitems:
            if z.product.digital == False:
                shipping = True
        return shipping        
        


    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total   

    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total       


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True )        
    quantity = models.IntegerField(default=0, null=True,blank=True)
    dated_added = models.DateTimeField(auto_now_add=True)
    

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAdress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True )
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    dated_added =models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
            return self.address
            #스팰링 수정 adress ㅠㅠ
        

store/forms.py
from django import forms
from django.forms import fields
from .models import Product,Comment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        labels = {
            'name': '성함',
            'description': '제품설명',
            'price': '가격',
            'digital': '디지탈제품',
            'image': '상품이미지',
        }


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username","email","password1","password2")

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user         


#모델 폼을 사용. 모델과 필드만 정해주면 자동으로 form이 작동
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        #fields = ('author', 'text',)
        fields = ['text']
        labels = {
            'text': '댓글쓰기',
        }

store/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic.base import TemplateView
from .models import *
import json
import datetime
from . 쿠키처리 import *
#추가
from django.views.generic import CreateView, DetailView,TemplateView,View
from django.contrib.auth.forms import UserCreationForm
from .forms import ProductForm,CreateUserForm,CommentForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib import messages




class StoreView(TemplateView):
    template_name = "store/상점.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Data = 장바구니데이타(self.request)
        cartItems = Data['cartItems']
        products = Product.objects.all()
        context['products'] = products
        context['cartItems'] = cartItems
        return context



def store(request):
    Data = 장바구니데이타(request)
    cartItems = Data['cartItems']

    products = Product.objects.all()
    context = {'products':products,'cartItems': cartItems }

    return render(request, 'store/상점.html', context)

class CartView(TemplateView):
    template_name = "store/장바구니.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Data = 장바구니데이타(self.request)
        cartItems = Data['cartItems']
        order = Data['order']
        items = Data['items']
        context['items'] = items
        context['order'] = order
        context['cartItems'] = cartItems
        return context



def cart(request):
    Data = 장바구니데이타(request)
    cartItems = Data['cartItems']
    order = Data['order']
    items = Data['items'] 

    context = {'items': items, 'order':order, 'cartItems': cartItems}

    return render(request, 'store/장바구니.html', context)

class CheckoutView(TemplateView):
    template_name = "store/결제.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Data = 장바구니데이타(self.request)
        cartItems = Data['cartItems']
        order = Data['order']
        items = Data['items']
        context['items'] = items
        context['order'] = order
        context['cartItems'] = cartItems
        return context


def checkout(request):
    
    Data = 장바구니데이타(request)
    cartItems = Data['cartItems']
    order = Data['order']
    items = Data['items']  

    context = {'items': items, 'order':order,'cartItems': cartItems}

    return render(request, 'store/결제.html', context)

class UpdatedItemView(View):
    def post(self, request, *args, **kwargs):
        #get 방식으로 하면 장바구니에 물건이 안담김, 수정
        data = json.loads(request.body)        
        productID = data['productID']
        action = data['action']        
        print('Product:', productID)
        print('Action:', action)

        customer = request.user.customer
        product = Product.objects.get(id=productID)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
        if action == 'add':
            orderItem.quantity = (orderItem.quantity + 1)
        elif action == 'remove':
            orderItem.quantity = (orderItem.quantity - 1)   

        orderItem.save()

        if orderItem.quantity <= 0:
            orderItem.delete()



        return JsonResponse('Item added', safe =False)


def updatedItem(request):
        data = json.loads(request.body)        
        productID = data['productID']
        action = data['action']        
        print('Product:', productID)
        print('Action:', action)

        customer = request.user.customer
        product = Product.objects.get(id=productID)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
        if action == 'add':
            orderItem.quantity = (orderItem.quantity + 1)
        elif action == 'remove':
            orderItem.quantity = (orderItem.quantity - 1)   

        orderItem.save()

        if orderItem.quantity <= 0:
            orderItem.delete()



        return JsonResponse('Item added', safe =False)    



@csrf_exempt


def processOrder(request):
    #print("Data:" , request.body)
    transation_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        
        

    else:
        customer,order = 손님주문(request,data)
        

    total = float(data['form']['total'])
    order.transation_id = transation_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    
    if order.shipping == True:
        ShippingAdress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],



        )            


    return JsonResponse('Payment Completed!', safe =False) 


class RegistrationView(CreateView):
    template_name = "store/registration.html"
    #form_class = UserCreationForm
    form_class = CreateUserForm
    success_url = "/"

class ProductDetailView(DetailView):
    template_name = "store/product_detail.html"
    queryset = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Data = 장바구니데이타(self.request)
        cartItems = Data['cartItems']
        context['cartItems'] = cartItems
        return context



class ProductAddView(CreateView):
    form_class = ProductForm
    template_name = "store/add_product.html"
    success_url = "/"        

def add_comment(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.product = product
            comment.save()
            return redirect('product_detail', pk=product.pk)
    else:
        form = CommentForm()

    return render(request, 'store/add_comment.html', {'form': form})
    #경로 주의 'add_comment_to_post.html' 아님 .212 참고 template_name = "store/add_product.html"
    #from django.shortcuts import redirect => 아니면 name error 나옴
    #코드를 줄이기 위해 context 를 바로 넣음. 따라서 다음과 같이 쓸 수 있음
    #context = {'form': form}
    #return render(request, 'store/add_comment_to_post.html', context)

@login_required
def comment_modify(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save()
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('product_detail', pk=comment.product.pk)
    else:
        form = CommentForm(instance=comment)    
    return render(request, 'store/add_comment.html', {'form': form})
#댓글 수정 함수는 댓글 등록 함수와 같은 형태    



@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('product_detail', pk=comment.product.pk)

store/templates/store/add_comment.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}
    <h1>새 덧글</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">쓰기</button>
    </form>
{% endblock %}

store/templates/store/add_comment_to_post.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}
    <h1>새 덧글</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">쓰기</button>
    </form>
{% endblock %}

store/templates/store/add_product.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}
<h3>나누면 재벌된다! 바자회 제품 등록!</h3>
<div class="row">
    <div class="col-lg-6">
        <div class="box">
            <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary">등록</button>
            </form>
        </div>
       
    </div>
</div>

{% endblock content %}

store/templates/store/login.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}
<h3>쇼핑몰 로그인</h3>
<div class="row">
    <div class="col-lg-6">
        <div class="box">
            <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary">로그인</button>
            </form>
        </div>
       
    </div>
</div>

{% endblock content %}

store/templates/store/product_detail.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}
<h3>제품명 : {{ product.name }}</h3>

          
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
      <article class="gallery-wrap"> 
      <div class="img-big-wrap">
        <div> <a href="#"><img src="{{ product.imageURL }}" class="img-fluid"></a></div>
      </div>
  
      </article>
          </aside>
          <aside class="col-sm-7">
      <article class="card-body p-5">
        <h3 class="title mb-3">{{ product.name }}</h3>

      <p class="price-detail-wrap"> 
        <span class="price h3 text-warning"> 
          <span class="currency">$</span><span class="num">{{ product.price }}</span>
        </span> 
      
      </p> <!-- price-detail-wrap .// -->
      <dl class="item-property">
        <dt>제품설명</dt>
        <dd><p>{{ product.description }} </p></dd>
      </dl>
      
   
        
        <hr>
        <button data-product={{product.id}} data-action="add" class="btn btn-success 장바구니업데이트">장바구니 담기</button>


    <hr>
  {% for comment in product.comments.all %}
    <!-- #product.comments.all 에서 루핑// -->
    {% if user.is_authenticated or comment.approved_comment %}
    <!-- 인증이 안되면 승인된 댓글은 보이나 스팸 댓글 지우는 행위에 참가 할 수 없게하기 위해 -->
    
    <div class="comment">
        <div class="editcomment">
            {{ comment.created_date }}
              {% if comment.modify_date %}
              (수정:{{ comment.modify_date }})
              {% endif %}
              
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}">💩</a>
            {% endif %}
            
            

            {% if request.user == comment.author %}
            <a href="{% url 'comment_modify' pk=comment.pk  %}" class="small">수정</a>,
            <a href="{% url 'comment_remove' pk=comment.pk  %}" class="small">삭제</a>
            {% endif %}
        </div>
        <strong>(🐺 :{{ comment.author }})</strong>
        <p>✒️ :{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
  {% empty %} 
    <p>앙직 댓글이 없어요~~</p>
{% endfor %}
{% if user.is_authenticated %}
                    
      <a class="btn btn-success" href="{% url 'add_comment' pk=product.pk %}">댓글추가</a>  

{% else %} 
<a href="{% url 'login' %}" class="btn btn-danger">로그인 후 댓글 달기</a>
{% endif %}

          </article> <!-- card-body.// -->
          </aside> <!-- col.// -->
        </div> <!-- row.// -->
      </div> <!-- card.// -->


      </div>
      <!--container.//-->
      </article>
        </div>


{% endblock content %}

store/templates/store/registration.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}
<h3>쇼핑몰 회원가입</h3>
<div class="row">
    <div class="col-lg-6">
        <div class="box">
            <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary">가입하기</button>
            </form>
        </div>
       
    </div>
</div>

{% endblock content %}

store/templates/store/결제.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}
<h3>결제</h3>
<div class="row">
    <div class="col-lg-6">
        <div class="box" id='폼감싼정보'>
            <form id='폼'>
                
                <div id="사용자정보">
                    <div>
                        <input required class="form-control" type="text" name="name" placeholder="성함..">
                    </div>
                    <div>
                        <input required class="form-control" type="email" name="email" placeholder="이메일..">
                    </div>              
                </div>
                <div id='배송정보'> 
                    <hr>
                    <p>배송 정보:</p>
                    <hr>
                    <div>
                        <input class="form-control" type="text" name="address" placeholder="주소와 전화번호">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="city" placeholder="도시..">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="state" placeholder="도..">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="zipcode" placeholder="우편 번호..">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="country" placeholder="국가..">
                    </div>
                </div>
                <hr>
                <input id='폼버튼' class="btn btn-success btn-block" type="submit" value="계속 진행">
            </form>
        </div>
        <br>
            <div class="box 숨기기" id="payment-info">
                <!--<small>결제 버튼이 여기에 추가될 예정</small>
                <button id="make-payment">💰돈 내기</button>-->
                <div id="paypal-button-container"></div>
            </div>
    </div>
    <div class="col-lg-6">
        <div class="box">
        <a class="btn btn-outline-secondary" href="{% url 'cart' %}">🔙장바구니로 돌아가기</a>
        <hr>
        <h3>주문 요약</h3>
        <hr>
        {% for item in items %}
        <div class="장바구니줄">
                <div style="flex:2"><img class="장바구니이미지" src="{{item.product.imageURL}}"></div>
                <div style="flex:2"><strong>{{item.product.name}}</strong></div>
                <div style="flex:1"><strong>${{item.product.price|floatformat:2}}</strong></div>
                <div style="flex:1"><strong>{{item.quantity}}</strong></div>

        </div>
        {% endfor %}
        <h5>제품 수: {{order.get_cart_items}} </h5>
        <h5>총합 : ${{order.get_cart_total|floatformat:2}} </h5>
    </div>
</div>

 <script src="https://www.paypal.com/sdk/js?client-id=AfGoMNgWwM1nkgan-DjQnJBeFTknkQk1eriR4OqPxUZpKQRFyejXeTMtp_G_l88C6fZqpIyZXCv5K45r&currency=USD"></script>

 <script>
        var total = '{{order.get_cart_total}}'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    submitFormData()
                    
                });
            }


        }).render('#paypal-button-container');
    </script>


<script type = "text/javascript">
    var shipping = '{{order.shipping}}'
    

    if (shipping == 'False'){
        document.getElementById('배송정보').innerHTML = ''
    }


    if (user != 'AnonymousUser'){
        document.getElementById('사용자정보').innerHTML = ''
    }

    if (shipping == 'False' && user != 'AnonymousUser'){
        document.getElementById('폼감싼정보').classList.add('숨기기');
        document.getElementById('payment-info').classList.remove('숨기기');
    }



    var form = document.getElementById('폼')
    form.addEventListener('submit', function(e) {
        e.preventDefault()
        document.getElementById('폼버튼').classList.add('숨기기')
        document.getElementById('payment-info').classList.remove('숨기기')



    })
    /*
    document.getElementById('make-payment').addEventListener('click', function(e){
        submitFormData()
    })
    */
    
    function submitFormData(){
        console.log('주문버튼 눌렀다')

        var userFormData ={
            'name':null,
            'email':null,
            'total':total,
        }

        var shippingInfo ={
            'address':null,
            'city':null,
            'state':null,
            'zipcode':null,


        }

        if(shipping != 'False'){
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value

        }

        if(user == 'AnonymousUser') {
            userFormData.name = form.name.value
            userFormData.email = form.email.value

        }
        
        console.log('배송정보:', shippingInfo)
        console.log('사용자정보:', userFormData)

    var url ='/process_order/'
    fetch(url,{
        method: 'POST',
        headers:{
            'Content-Type':'application/json',
            'X-CSRFToken': csrftoken

        },
        body:JSON.stringify({'form': userFormData,'shipping' : shippingInfo})

    })

    .then((response) =>{
        return response.json()
    })
    .then((data) =>{
        console.log('Sucess:', data);
        alert('주문이 완료 되었습니다');
        cart = {}
        document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
        window.location.href= "{% url 'store' %}"
    })

    }


</script>
{% endblock content %}

store/templates/store/메인.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>쇼핑</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS only -->
    
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type ="text/css" href="{% static 'css/main.css' %}">
    
        <script type ="text/javascript">
            var user = '{{request.user}}'

            function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');

        function getCookie(name) {
        // 쿠키 문자열을 분할하고 배열의 모든 개별 이름 = 값 쌍을 가져옵니다.
            var cookieArr = document.cookie.split(";");

            // 배열 요소를 통해 반복
            for(var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* 쿠키 이름 시작 부분의 공백 제거 주어진 문자열과 비교 */
                if(name == cookiePair[0].trim()) {
                    // 쿠키 값을 디코딩하고 반환
                    return decodeURIComponent(cookiePair[1]);
                }
            }

                // 찾을 수없는 경우 null 반환
                return null;
        }

		var cart = JSON.parse(getCookie('cart'))
        if (cart == undefined) {
            cart = {}
            console.log('장바구니 쿠키 완성!')
            document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }



        console.log('cart:', cart)

        </script>

        

    
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        
            <a class="navbar-brand" href="{% url 'store' %}">울트라 쇼핑몰</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'add_product' %}">재벌몰</a>
                </li>
                
                
                </ul>
                <div class="form-inline my-2 my-lg-0">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="btn btn-danger">{{user.username}}님 로그아웃</a>
                    {% else %} 
                    <a href="{% url 'login' %}" class="btn btn-danger">로그인</a>
                    <a href="{% url 'register' %}" class="btn btn-danger">가입</a>
                    {% endif %}
                    <a href ="{% url 'cart' %}">
                        <img src="{% static 'images/shopping-cart-16.png'%}">
                    </a>
                    <b>{{cartItems}}</b></p>
                </div>
                
            </div>
        <!-- 부트스트랩 폼 디자인 참고 https://getbootstrap.com/docs/4.0/components/navbar/#forms -->    
        <form class="form-inline" action="{% url 'search:searchResult' %}" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="검색" name="kw">
            
        </form>
        </nav>
        <hr>
        <div class="container">
            <p>
            {% block content %}

            {% endblock content %}

        </div>
    
       
            <!-- JavaScript Bundle with Popper -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/cart.js'%}"></script>
        
    </body>
</html>

store/templates/store/상점.html
{% extends 'store/메인.html'%}
{% load static %}
{% block content %}

<div class="row">
    {% for product in products %}
    <div class="col-lg-4">
        <div class= "box">
        <img width=100% src="{{product.imageURL}}">
        <h6><strong>{{product.name}}</strong></h6>
        {{product.description}}
        <hr>
        <button data-product={{product.id}} data-action="add" class="btn btn-success 장바구니업데이트">장바구니 담기</button>
        <a href="product/{{product.pk}}" class="btn btn-success">보기</a>
        <h4 style="display: inline-block; float: right"><strong>${{product.price|floatformat:2}}</strong></h4>
				
        </div>
       
    </div>
    {% endfor %} 
   
  
</div>
{% endblock content %}